name = "Noise"
uuid = "81d43f40-5267-43b7-ae1c-8b967f377efa"
authors = ["Felix Wechsler <fxw+github@mailbox.org"]
version = "0.3.3"

[deps]
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
PoissonRandom = "e409e4f3-bfea-5376-8464-e040bb5c01ab"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ImageCore = "0.5, 0.6, 0.7, 0.8, 0.9, 0.10"
PoissonRandom = "0.4"
julia = "1"

[extras]
ColorVectorSpace = "c3611d14-8923-5661-9e6a-0046d554d3a4"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Statistics", "ImageCore", "ColorVectorSpace"]
